## Reading Data From Different Sources

In [4]:
import pandas as pd
from io import StringIO
Data = '{"Employee_name": "James", "Email": "james@gmail.com", "Job_profile": {"title1": "Team Lead", "title2": "Sr Developer"}}'
df = pd.read_json(StringIO(Data))

In [5]:
df

       Employee_name            Email   Job_profile
title1         James  james@gmail.com     Team Lead
title2         James  james@gmail.com  Sr Developer

In [6]:
df.to_json() # Convert DataFrame to JSON string

'{"Employee_name":{"title1":"James","title2":"James"},"Email":{"title1":"james@gmail.com","title2":"james@gmail.com"},"Job_profile":{"title1":"Team Lead","title2":"Sr Developer"}}'

In [7]:
df.to_json(orient='index') # Convert DataFrame to JSON string with index orientation

'{"title1":{"Employee_name":"James","Email":"james@gmail.com","Job_profile":"Team Lead"},"title2":{"Employee_name":"James","Email":"james@gmail.com","Job_profile":"Sr Developer"}}'

In [8]:
df.to_json(orient='records') # Convert DataFrame to JSON string with 'records' orientation

'[{"Employee_name":"James","Email":"james@gmail.com","Job_profile":"Team Lead"},{"Employee_name":"James","Email":"james@gmail.com","Job_profile":"Sr Developer"}]'

In [10]:
# !pip install lxml

Defaulting to user installation because normal site-packages is not writeable
Collecting lxml
  Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl.metadata (3.7 kB)
Downloading lxml-6.0.2-cp313-cp313-win_amd64.whl (4.0 MB)
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   ---------------------------------------- 0.0/4.0 MB ? eta -:--:--
   -- ------------------------------------- 0.3/4.0 MB ? eta -:--:--
   ----- ---------------------------------- 0.5/4.0 MB 1.1 MB/s eta 0:00:04
   ------- -------------------------------- 0.8/4.0 MB 1.2 MB/s eta 0:00:03
   ------------- -------------------------- 1.3/4.0 MB 1.4 MB/s eta 0:00:02
   --------------- ------------------------ 1.6/4.0 MB 1.4 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.5 MB/s eta 0:00:02
   ------------------ --------------------- 1.8/4.0 MB 1.5 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.2 MB/s eta 0:00:02
   -------------------- ------------------- 2.1/4.0 MB 1.2 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.0 MB/s eta 0:00:02
   ----------------------- ---------------- 2.4/4.0 MB 1.0 MB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 975.0 kB/s eta 0:00:02
   -------------------------- ------------- 2.6/4.0 MB 975.0 kB/s eta 0:00:02
   ---------------------------- ----------- 2.9/4.0 MB 946.5 kB/s eta 0:00:02
   ------------------------------- -------- 3.1/4.0 MB 954.1 kB/s eta 0:00:01
   ------------------------------- -------- 3.1/4.0 MB 954.1 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 962.8 kB/s eta 0:00:01
   ------------------------------------ --- 3.7/4.0 MB 962.8 kB/s eta 0:00:01
   ---------------------------------------- 4.0/4.0 MB 970.7 kB/s eta 0:00:00
Installing collected packages: lxml
Successfully installed lxml-6.0.2

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [14]:
# !pip install html5lib
# !pip install beautifulsoup4

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: html5lib in c:\users\hp\appdata\roaming\python\python313\site-packages (1.1)
Requirement already satisfied: six>=1.9 in c:\users\hp\appdata\roaming\python\python313\site-packages (from html5lib) (1.17.0)
Requirement already satisfied: webencodings in c:\users\hp\appdata\roaming\python\python313\site-packages (from html5lib) (0.5.1)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Defaulting to user installation because normal site-packages is not writeable

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016121056120>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016121051D10>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016121051F90>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016121052210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/beautifulsoup4/
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x0000016121052490>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /simple/beautifulsoup4/
ERROR: Could not find a version that satisfies the requirement beautifulsoup4 (from versions: none)

[notice] A new release of pip is available: 25.1.1 -> 26.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip
ERROR: No matching distribution found for beautifulsoup4

In [18]:
url = "https://www.fdic.gov/bank-failures/failed-bank-list"

df = pd.read_html(url)

In [19]:
df[0]

,Bank Name,City,State,Cert,Acquiring Institution,Closing Date,Fund Sort ascending
0,Metropolitan Capital Bank & Trust,Chicago,Illinois,57488,First Independence Bank,"January 30, 2026",10550
1,The Santa Anna National Bank,Santa Anna,Texas,5520,Coleman County State Bank,"June 27, 2025",10549
2,Pulaski Savings Bank,Chicago,Illinois,28611,Millennium Bank,"January 17, 2025",10548
3,The First National Bank of Lindsay,Lindsay,Oklahoma,4134,First Bank & Trust Co.,"October 18, 2024",10547
4,Republic First Bank dba Republic Bank,Philadelphia,Pennsylvania,27332,"Fulton Bank, National Association","April 26, 2024",10546
5,Citizens Bank,Sac City,Iowa,8758,Iowa Trust & Savings Bank,"November 3, 2023",10545
6,Heartland Tri-State Bank,Elkhart,Kansas,25851,"Dream First Bank, N.A.","July 28, 2023",10544
7,First Republic Bank,San Francisco,California,59017,"JPMorgan Chase Bank, N.A.","May 1, 2023",10543
8,Signature Bank,New York,New York,57053,"Flagstar Bank, N.A.","March 12, 2023",10540
9,Silicon Valley Bank,Santa Clara,California,24735,First–Citizens Bank & Trust Company,"March 10, 2023",10539
10,Almena State Bank,Almena,Kansas,15426,Equity Bank,"October 23, 2020",10538
11,First City Bank of Florida,Fort Walton Beach,Florida,16748,"United Fidelity Bank, fsb","October 16, 2020",10537
12,The First State Bank,Barboursville,West Virginia,14361,"MVB Bank, Inc.","April 3, 2020",10536
13,Ericson State Bank,Ericson,Nebraska,18265,Farmers and Merchants Bank,"February 14, 2020",10535
14,City National Bank of New Jersey,Newark,New Jersey,21111,Industrial Bank,"November 1, 2019",10534
15,Resolute Bank,Maumee,Ohio,58317,Buckeye State Bank,"October 25, 2019",10533
16,Louisa Community Bank,Louisa,Kentucky,58112,Kentucky Farmers Bank Corporation,"October 25, 2019",10532
17,The Enloe State Bank,Cooper,Texas,10716,"Legend Bank, N. A.","May 31, 2019",10531
18,Washington Federal Bank for Savings,Chicago,Illinois,30570,Royal Savings Bank,"December 15, 2017",10530
19,The Farmers and Merchants State Bank of Argonia,Argonia,Kansas,17719,Conway Bank,"October 13, 2017",10529
20,Fayette County Bank,Saint Elmo,Illinois,1802,"United Fidelity Bank, fsb","May 26, 2017",10528
21,"Guaranty Bank, (d/b/a BestBank in Georgia & Mi...",Milwaukee,Wisconsin,30003,First-Citizens Bank & Trust Company,"May 5, 2017",10527
22,First NBC Bank,New Orleans,Louisiana,58302,Whitney Bank,"April 28, 2017",10526
23,Proficio Bank,Cottonwood Heights,Utah,35495,Cache Valley Bank,"March 3, 2017",10525
24,Seaway Bank and Trust Company,Chicago,Illinois,19328,State Bank of Texas,"January 27, 2017",10524

In [ ]:
# %pip install requests

In [ ]:
import requests
import pandas as pd

url = 'https://en.wikipedia.org/wiki/Mobile_country_code'
headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'}
response = requests.get(url, headers=headers)
tables = pd.read_html(response.text, match="Country", header=0)
df = tables[0]
print(df.head())

   Mobile country code                                    Country ISO 3166  \
0                  289                                 A Abkhazia    GE-AB
1                  412                                Afghanistan       AF
2                  276                                    Albania       AL
3                  603                                    Algeria       DZ
4                  544  American Samoa (United States of America)       AS

                             Mobile network codes National MNC authority  \
0        List of mobile network codes in Abkhazia                    NaN
1     List of mobile network codes in Afghanistan                    NaN
2         List of mobile network codes in Albania                    NaN
3         List of mobile network codes in Algeria                    NaN
4  List of mobile network codes in American Samoa                    NaN

                    Remarks
0  MCC is not listed by ITU
1                       NaN
2                       NaN
3                       NaN
4                       NaN

C:\Users\HP\AppData\Local\Temp\ipykernel_24664\3881964538.py:7: FutureWarning: Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  tables = pd.read_html(response.text, match="Country", header=0)